"""
Constants
"""

STATION_FIELDS_D = {
    'agency_cd': 'Agency',
    'site_no': 'Site identification number',
    'station_nm': 'Site name',
    'site_tp_cd': 'Site type',
    'lat_va': 'DMS latitude',
    'long_va': 'DMS longitude',
    'dec_lat_va': 'Decimal latitude',
    'dec_long_va': 'Decimal longitude',
    'coord_meth_cd': 'Latitude-longitude method',
    'coord_acy_cd': 'Latitude-longitude accuracy',
    'coord_datum_cd': 'Latitude-longitude datum',
    'dec_coord_datum_cd': 'Decimal Latitude-longitude datum',
    'district_cd': 'District',
    'state_cd': 'State',
    'county_cd': 'County',
    'country_cd': 'Country',
    'land_net_ds': 'Land net location description',
    'map_nm': 'Name of location map',
    'map_scale_fc': 'Scale of location map',
    'alt_va': 'Altitude of Gage/land surface',
    'alt_meth_cd': 'Method altitude determined',
    'alt_acy_va': 'Altitude accuracy',
    'alt_datum_cd': 'Altitude datum',
    'huc_cd': 'Subbasin hydrologic unit',
    'basin_cd': 'Drainage basin',
    'topo_cd': 'Topographic setting',
    'instruments_cd': 'Flags for instruments at site',
    'construction_dt': 'Date of first construction',
    'inventory_dt': 'Date site established or inventoried',
    'drain_area_va': 'Drainage area',
    'contrib_drain_area_va': 'Contributing drainage area',
    'tz_cd': 'Time Zone abbreviation',
    'local_time_fg': 'Site honors Daylight Savings Time',
    'reliability_cd': 'Data reliability',
    'gw_file_cd': 'Data-other GW files',
    'nat_aqfr_cd': 'National aquifer',
    'aqfr_cd': 'Local aquifer',
    'aqfr_type_cd': 'Local aquifer type',
    'well_depth_va': 'Well depth',
    'hole_depth_va': 'Hole depth',
    'depth_src_cd': 'Source of depth data',
    'project_no': 'Project number',
}


US_STATES = [
    {'name': 'Alabama', 'abbreviation': 'AL'},
    {'name': 'Alaska', 'abbreviation': 'AK'},
    {'name': 'American Samoa', 'abbreviation': 'AS'},
    {'name': 'Arizona', 'abbreviation': 'AZ'},
    {'name': 'Arkansas', 'abbreviation': 'AR'},
    {'name': 'California', 'abbreviation': 'CA'},
    {'name': 'Colorado', 'abbreviation': 'CO'},
    {'name': 'Connecticut', 'abbreviation': 'CT'},
    {'name': 'Delaware', 'abbreviation': 'DE'},
    {'name': 'District Of Columbia', 'abbreviation': 'DC'},
    {'name': 'Federated States Of Micronesia', 'abbreviation': 'FM'},
    {'name': 'Florida', 'abbreviation': 'FL'},
    {'name': 'Georgia', 'abbreviation': 'GA'},
    {'name': 'Guam', 'abbreviation': 'GU'},
    {'name': 'Hawaii', 'abbreviation': 'HI'},
    {'name': 'Idaho', 'abbreviation': 'ID'},
    {'name': 'Illinois', 'abbreviation': 'IL'},
    {'name': 'Indiana', 'abbreviation': 'IN'},
    {'name': 'Iowa', 'abbreviation': 'IA'},
    {'name': 'Kansas', 'abbreviation': 'KS'},
    {'name': 'Kentucky', 'abbreviation': 'KY'},
    {'name': 'Louisiana', 'abbreviation': 'LA'},
    {'name': 'Maine', 'abbreviation': 'ME'},
    {'name': 'Marshall Islands', 'abbreviation': 'MH'},
    {'name': 'Maryland', 'abbreviation': 'MD'},
    {'name': 'Massachusetts', 'abbreviation': 'MA'},
    {'name': 'Michigan', 'abbreviation': 'MI'},
    {'name': 'Minnesota', 'abbreviation': 'MN'},
    {'name': 'Mississippi', 'abbreviation': 'MS'},
    {'name': 'Missouri', 'abbreviation': 'MO'},
    {'name': 'Montana', 'abbreviation': 'MT'},
    {'name': 'Nebraska', 'abbreviation': 'NE'},
    {'name': 'Nevada', 'abbreviation': 'NV'},
    {'name': 'New Hampshire', 'abbreviation': 'NH'},
    {'name': 'New Jersey', 'abbreviation': 'NJ'},
    {'name': 'New Mexico', 'abbreviation': 'NM'},
    {'name': 'New York', 'abbreviation': 'NY'},
    {'name': 'North Carolina', 'abbreviation': 'NC'},
    {'name': 'North Dakota', 'abbreviation': 'ND'},
    {'name': 'Northern Mariana Islands', 'abbreviation': 'MP'},
    {'name': 'Ohio', 'abbreviation': 'OH'},
    {'name': 'Oklahoma', 'abbreviation': 'OK'},
    {'name': 'Oregon', 'abbreviation': 'OR'},
    {'name': 'Palau', 'abbreviation': 'PW'},
    {'name': 'Pennsylvania', 'abbreviation': 'PA'},
    {'name': 'Puerto Rico', 'abbreviation': 'PR'},
    {'name': 'Rhode Island', 'abbreviation': 'RI'},
    {'name': 'South Carolina', 'abbreviation': 'SC'},
    {'name': 'South Dakota', 'abbreviation': 'SD'},
    {'name': 'Tennessee', 'abbreviation': 'TN'},
    {'name': 'Texas', 'abbreviation': 'TX'},
    {'name': 'Utah', 'abbreviation': 'UT'},
    {'name': 'Vermont', 'abbreviation': 'VT'},
    {'name': 'Virgin Islands', 'abbreviation': 'VI'},
    {'name': 'Virginia', 'abbreviation': 'VA'},
    {'name': 'Washington', 'abbreviation': 'WA'},
    {'name': 'West Virginia', 'abbreviation': 'WV'},
    {'name': 'Wisconsin', 'abbreviation': 'WI'},
    {'name': 'Wyoming', 'abbreviation': 'WY'}
]

SORT_TOP = ('DISCHARGE', 'GAGE HEIGHT', 'TEMPERATURE', 'DEPTH TO WATER LEVEL')
